name: Sync with Upstream

on:
  schedule:
    - cron: '50 15 * * 5' # Runs every Friday at 15:50 GMT
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/ethereum-optimism/optimism.git

      - name: Create branch and merge upstream/develop
        id: create_pr_branch
        run: |
          PR_BRANCH="sync/upstream-merge-$(date +%s)"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch upstream
          git checkout -b "$PR_BRANCH" upstream/develop
          git merge upstream/develop --no-edit
          git push origin "$PR_BRANCH"
          echo "pr_branch=$PR_BRANCH" >> $GITHUB_OUTPUT

      - name: Create PR for merging upstream/develop into develop
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_BRANCH="${{ steps.create_pr_branch.outputs.pr_branch }}"
          CURRENT_DATE=$(date '+%Y-%m-%d')

          # Get the last assignee and find the next one in the list
          ASSIGNEES=(nyospe excaliborr wintercode-co michalsidzej)
          NUM_ASSIGNEES=${#ASSIGNEES[@]}

          LAST_ASSIGNEE=$(gh pr list --repo "$GITHUB_REPOSITORY" --author "github-actions[bot]" --state all --limit 1 --json assignees --jq '.[0].assignees[0].login // empty')

          echo "Last assignee was: $LAST_ASSIGNEE"

          if [[ -z "$LAST_ASSIGNEE" ]]; then
            INDEX=-1
          else
            INDEX=-1
            for i in "${!ASSIGNEES[@]}"; do
              if [[ "${ASSIGNEES[$i]}" == "$LAST_ASSIGNEE" ]]; then
                INDEX=$i
                break
              fi
            done
          fi

          NEXT_INDEX=$(( (INDEX + 1) % NUM_ASSIGNEES ))
          ASSIGNEE=${ASSIGNEES[$NEXT_INDEX]}

          echo "Assigning PR to: $ASSIGNEE"

          gh pr create --repo "$GITHUB_REPOSITORY" --base develop --head "$GITHUB_REPOSITORY_OWNER:$PR_BRANCH" \
            --title "Syncing with upstream on $CURRENT_DATE" \
            --body "Merging changes from upstream/develop." \
            --reviewer "nyospe,excaliborr,wintercode-co,michalsidzej" \
            --assignee "$ASSIGNEE"
